### ISSUE TITLE
[FIKA DEDICATED TODO]

### ISSUE THREAD

**Issue by Lacyway** [project-fika/Fika-Server#57]
- [x] Filter item sending dedi profiles
- [x] Sounds are being played on dedi, disable by default
- [x] Set to absolute lowest graphics by default
- [x] More elegant way to determine if a player is a dedicated host when loading in a remote profile
- [ ] Handle different unnatural disconnect types
- [ ] Add timeout to "Wait for other players to finish loading" for the dedicated host
- [ ] Only show 'Use Dedicated' if one is available
- [ ] Implement partial or no rendering

**Comment by maxomatic458** [comment]
* [ ] Add a Terragroup Labs access card to the dedicated clients inventory when needed

**Comment by Lacyway** [comment]
> * [x]  Add a Terragroup Labs access card to the dedicated clients inventory when needed

Just pushed a commit that should resolve this, let me know if it works.

**Comment by Lacyway** [comment]
Moving to dedi repo
